/-
  Root module for the `proofs/lean/` Lake project.
-/

import MPRD_Theorem
import MPRD_Alignment_Combined
import MPRD_ExecutionLifecycle
import MPRD_ExecutionGate
import MPRD_ExecutionCommitmentBindings
import MPRD_ExecutionBoundary
import MPRD_ExecutionReadyPacketBoundary
import MPRD_ExecutionReadyPacketRefinement
import MPRD_ExecutionReadyRefinementWitnessCompiler
import MPRD_ExecutionReadyRuntimeRefinement
import MPRD_ExecutionBindingVectorPacketBoundary
import MPRD_ExecutionBoundaryRefinementPacketBoundary
import MPRD_AttestationReadyExecutionAuthorizationBoundary
import MPRD_ExecutionAuthorizationMetadataPacketBoundary
import MPRD_ExecutionAuthorizationWitnessProjection
import MPRD_ExecutionRegistryBridgeWitnessProjection
import MPRD_SelectorContractBinding
import MPRD_TauPolicyAuthority
import MPRD_GovernedPolicySource
import MPRD_GovernedSourceIntentBoundary
import MPRD_GovernedSourceArtifactWitness
import MPRD_GovernanceGateAuthorization
import MPRD_GovernanceStateLinkage
import MPRD_GovernanceExecutionBridge
import MPRD_SignedRegistryCheckpointBridge
import MPRD_SignedRegistryBridgeMetadataPacketBoundary
import MPRD_SignedRegistryExecutionBoundaryRefinement
import MPRD_SignedRegistryExecutionMetadataPacketBoundary
import MPRD_SignedRegistryExecutionRefinementPacketBoundary
import MPRD_SignedRegistryExecutionRefinementWitnessCompiler
import MPRD_SignedRegistryExecutionExactPacketWitnessCompiler
import MPRD_SignedRegistryExecutionExactPacketRuntimeRefinement
import MPRD_SignedRegistryExecutionArtifactRuntimeRefinement
import MPRD_SignedRegistryBridgeWitnessBoundary
import MPRD_SignedRegistryExecutionBoundary
import MPRD_SignedRegistryServeEndToEndRefinement
import MPRD_SignedRegistryServeExecutionBoundaryRefinement
import MPRD_SignedRegistryServeBoundary
import MPRD_SignedRegistryServeReadyPacketBoundary
import MPRD_SignedRegistryServeAttestationHashBoundary
import MPRD_SignedRegistryServeAttestationHashReadyPacketBoundary
import MPRD_SignedRegistryServeAttestationHashRefinement
import MPRD_SignedRegistryServeAttestationHashArtifactBoundary
import MPRD_SignedRegistryServeAttestationHashExactPacketRefinement
import MPRD_SignedRegistryServeAttestationHashIdempotentHttpComposition
import MPRD_SignedRegistryServeIdempotentFileBoundary
import MPRD_SignedRegistryServeIdempotentHttpBoundary
import MPRD_RegistryPolicyAuthority
import MPRD_ParallelIndependenceOracle
import TauTables_SelectSet

-- No declarations needed here; importing ensures the files typecheck.
